// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft_serverpb.proto

#ifndef PROTOBUF_raft_5fserverpb_2eproto__INCLUDED
#define PROTOBUF_raft_5fserverpb_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "eraftpb.pb.h"
#include "metapb.pb.h"
// @@protoc_insertion_point(includes)

namespace raft_serverpb {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_raft_5fserverpb_2eproto();
void protobuf_InitDefaults_raft_5fserverpb_2eproto();
void protobuf_AssignDesc_raft_5fserverpb_2eproto();
void protobuf_ShutdownFile_raft_5fserverpb_2eproto();

class KeyValue;
class RaftApplyState;
class RaftLocalState;
class RaftMessage;
class RaftSnapshotData;
class RaftTruncatedState;
class RegionLocalState;
class StoreIdent;

enum PeerState {
  Normal = 0,
  Applying = 1,
  Tombstone = 2
};
bool PeerState_IsValid(int value);
const PeerState PeerState_MIN = Normal;
const PeerState PeerState_MAX = Tombstone;
const int PeerState_ARRAYSIZE = PeerState_MAX + 1;

const ::google::protobuf::EnumDescriptor* PeerState_descriptor();
inline const ::std::string& PeerState_Name(PeerState value) {
  return ::google::protobuf::internal::NameOfEnum(
    PeerState_descriptor(), value);
}
inline bool PeerState_Parse(
    const ::std::string& name, PeerState* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PeerState>(
    PeerState_descriptor(), name, value);
}
// ===================================================================

class RaftMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raft_serverpb.RaftMessage) */ {
 public:
  RaftMessage();
  virtual ~RaftMessage();

  RaftMessage(const RaftMessage& from);

  inline RaftMessage& operator=(const RaftMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RaftMessage& default_instance();

  static const RaftMessage* internal_default_instance();

  void Swap(RaftMessage* other);

  // implements Message ----------------------------------------------

  inline RaftMessage* New() const { return New(NULL); }

  RaftMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RaftMessage& from);
  void MergeFrom(const RaftMessage& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RaftMessage* other);
  void UnsafeMergeFrom(const RaftMessage& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 region_id = 1;
  bool has_region_id() const;
  void clear_region_id();
  static const int kRegionIdFieldNumber = 1;
  ::google::protobuf::uint64 region_id() const;
  void set_region_id(::google::protobuf::uint64 value);

  // optional .metapb.Peer from_peer = 2;
  bool has_from_peer() const;
  void clear_from_peer();
  static const int kFromPeerFieldNumber = 2;
  const ::metapb::Peer& from_peer() const;
  ::metapb::Peer* mutable_from_peer();
  ::metapb::Peer* release_from_peer();
  void set_allocated_from_peer(::metapb::Peer* from_peer);

  // optional .metapb.Peer to_peer = 3;
  bool has_to_peer() const;
  void clear_to_peer();
  static const int kToPeerFieldNumber = 3;
  const ::metapb::Peer& to_peer() const;
  ::metapb::Peer* mutable_to_peer();
  ::metapb::Peer* release_to_peer();
  void set_allocated_to_peer(::metapb::Peer* to_peer);

  // optional .eraftpb.Message message = 4;
  bool has_message() const;
  void clear_message();
  static const int kMessageFieldNumber = 4;
  const ::eraftpb::Message& message() const;
  ::eraftpb::Message* mutable_message();
  ::eraftpb::Message* release_message();
  void set_allocated_message(::eraftpb::Message* message);

  // optional .metapb.RegionEpoch region_epoch = 5;
  bool has_region_epoch() const;
  void clear_region_epoch();
  static const int kRegionEpochFieldNumber = 5;
  const ::metapb::RegionEpoch& region_epoch() const;
  ::metapb::RegionEpoch* mutable_region_epoch();
  ::metapb::RegionEpoch* release_region_epoch();
  void set_allocated_region_epoch(::metapb::RegionEpoch* region_epoch);

  // optional bool is_tombstone = 6;
  bool has_is_tombstone() const;
  void clear_is_tombstone();
  static const int kIsTombstoneFieldNumber = 6;
  bool is_tombstone() const;
  void set_is_tombstone(bool value);

  // optional bytes start_key = 7;
  bool has_start_key() const;
  void clear_start_key();
  static const int kStartKeyFieldNumber = 7;
  const ::std::string& start_key() const;
  void set_start_key(const ::std::string& value);
  void set_start_key(const char* value);
  void set_start_key(const void* value, size_t size);
  ::std::string* mutable_start_key();
  ::std::string* release_start_key();
  void set_allocated_start_key(::std::string* start_key);

  // optional bytes end_key = 8;
  bool has_end_key() const;
  void clear_end_key();
  static const int kEndKeyFieldNumber = 8;
  const ::std::string& end_key() const;
  void set_end_key(const ::std::string& value);
  void set_end_key(const char* value);
  void set_end_key(const void* value, size_t size);
  ::std::string* mutable_end_key();
  ::std::string* release_end_key();
  void set_allocated_end_key(::std::string* end_key);

  // @@protoc_insertion_point(class_scope:raft_serverpb.RaftMessage)
 private:
  inline void set_has_region_id();
  inline void clear_has_region_id();
  inline void set_has_from_peer();
  inline void clear_has_from_peer();
  inline void set_has_to_peer();
  inline void clear_has_to_peer();
  inline void set_has_message();
  inline void clear_has_message();
  inline void set_has_region_epoch();
  inline void clear_has_region_epoch();
  inline void set_has_is_tombstone();
  inline void clear_has_is_tombstone();
  inline void set_has_start_key();
  inline void clear_has_start_key();
  inline void set_has_end_key();
  inline void clear_has_end_key();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr start_key_;
  ::google::protobuf::internal::ArenaStringPtr end_key_;
  ::metapb::Peer* from_peer_;
  ::metapb::Peer* to_peer_;
  ::eraftpb::Message* message_;
  ::metapb::RegionEpoch* region_epoch_;
  ::google::protobuf::uint64 region_id_;
  bool is_tombstone_;
  friend void  protobuf_InitDefaults_raft_5fserverpb_2eproto_impl();
  friend void  protobuf_AddDesc_raft_5fserverpb_2eproto_impl();
  friend void protobuf_AssignDesc_raft_5fserverpb_2eproto();
  friend void protobuf_ShutdownFile_raft_5fserverpb_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<RaftMessage> RaftMessage_default_instance_;

// -------------------------------------------------------------------

class RaftTruncatedState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raft_serverpb.RaftTruncatedState) */ {
 public:
  RaftTruncatedState();
  virtual ~RaftTruncatedState();

  RaftTruncatedState(const RaftTruncatedState& from);

  inline RaftTruncatedState& operator=(const RaftTruncatedState& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RaftTruncatedState& default_instance();

  static const RaftTruncatedState* internal_default_instance();

  void Swap(RaftTruncatedState* other);

  // implements Message ----------------------------------------------

  inline RaftTruncatedState* New() const { return New(NULL); }

  RaftTruncatedState* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RaftTruncatedState& from);
  void MergeFrom(const RaftTruncatedState& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RaftTruncatedState* other);
  void UnsafeMergeFrom(const RaftTruncatedState& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 index = 1;
  bool has_index() const;
  void clear_index();
  static const int kIndexFieldNumber = 1;
  ::google::protobuf::uint64 index() const;
  void set_index(::google::protobuf::uint64 value);

  // optional uint64 term = 2;
  bool has_term() const;
  void clear_term();
  static const int kTermFieldNumber = 2;
  ::google::protobuf::uint64 term() const;
  void set_term(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:raft_serverpb.RaftTruncatedState)
 private:
  inline void set_has_index();
  inline void clear_has_index();
  inline void set_has_term();
  inline void clear_has_term();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::uint64 index_;
  ::google::protobuf::uint64 term_;
  friend void  protobuf_InitDefaults_raft_5fserverpb_2eproto_impl();
  friend void  protobuf_AddDesc_raft_5fserverpb_2eproto_impl();
  friend void protobuf_AssignDesc_raft_5fserverpb_2eproto();
  friend void protobuf_ShutdownFile_raft_5fserverpb_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<RaftTruncatedState> RaftTruncatedState_default_instance_;

// -------------------------------------------------------------------

class KeyValue : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raft_serverpb.KeyValue) */ {
 public:
  KeyValue();
  virtual ~KeyValue();

  KeyValue(const KeyValue& from);

  inline KeyValue& operator=(const KeyValue& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const KeyValue& default_instance();

  static const KeyValue* internal_default_instance();

  void Swap(KeyValue* other);

  // implements Message ----------------------------------------------

  inline KeyValue* New() const { return New(NULL); }

  KeyValue* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const KeyValue& from);
  void MergeFrom(const KeyValue& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(KeyValue* other);
  void UnsafeMergeFrom(const KeyValue& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes key = 1;
  bool has_key() const;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  void set_key(const char* value);
  void set_key(const void* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // optional bytes value = 2;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  void set_value(const char* value);
  void set_value(const void* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:raft_serverpb.KeyValue)
 private:
  inline void set_has_key();
  inline void clear_has_key();
  inline void set_has_value();
  inline void clear_has_value();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  friend void  protobuf_InitDefaults_raft_5fserverpb_2eproto_impl();
  friend void  protobuf_AddDesc_raft_5fserverpb_2eproto_impl();
  friend void protobuf_AssignDesc_raft_5fserverpb_2eproto();
  friend void protobuf_ShutdownFile_raft_5fserverpb_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<KeyValue> KeyValue_default_instance_;

// -------------------------------------------------------------------

class RaftSnapshotData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raft_serverpb.RaftSnapshotData) */ {
 public:
  RaftSnapshotData();
  virtual ~RaftSnapshotData();

  RaftSnapshotData(const RaftSnapshotData& from);

  inline RaftSnapshotData& operator=(const RaftSnapshotData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RaftSnapshotData& default_instance();

  static const RaftSnapshotData* internal_default_instance();

  void Swap(RaftSnapshotData* other);

  // implements Message ----------------------------------------------

  inline RaftSnapshotData* New() const { return New(NULL); }

  RaftSnapshotData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RaftSnapshotData& from);
  void MergeFrom(const RaftSnapshotData& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RaftSnapshotData* other);
  void UnsafeMergeFrom(const RaftSnapshotData& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .metapb.Region region = 1;
  bool has_region() const;
  void clear_region();
  static const int kRegionFieldNumber = 1;
  const ::metapb::Region& region() const;
  ::metapb::Region* mutable_region();
  ::metapb::Region* release_region();
  void set_allocated_region(::metapb::Region* region);

  // optional uint64 file_size = 2;
  bool has_file_size() const;
  void clear_file_size();
  static const int kFileSizeFieldNumber = 2;
  ::google::protobuf::uint64 file_size() const;
  void set_file_size(::google::protobuf::uint64 value);

  // repeated .raft_serverpb.KeyValue data = 3;
  int data_size() const;
  void clear_data();
  static const int kDataFieldNumber = 3;
  const ::raft_serverpb::KeyValue& data(int index) const;
  ::raft_serverpb::KeyValue* mutable_data(int index);
  ::raft_serverpb::KeyValue* add_data();
  ::google::protobuf::RepeatedPtrField< ::raft_serverpb::KeyValue >*
      mutable_data();
  const ::google::protobuf::RepeatedPtrField< ::raft_serverpb::KeyValue >&
      data() const;

  // @@protoc_insertion_point(class_scope:raft_serverpb.RaftSnapshotData)
 private:
  inline void set_has_region();
  inline void clear_has_region();
  inline void set_has_file_size();
  inline void clear_has_file_size();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::raft_serverpb::KeyValue > data_;
  ::metapb::Region* region_;
  ::google::protobuf::uint64 file_size_;
  friend void  protobuf_InitDefaults_raft_5fserverpb_2eproto_impl();
  friend void  protobuf_AddDesc_raft_5fserverpb_2eproto_impl();
  friend void protobuf_AssignDesc_raft_5fserverpb_2eproto();
  friend void protobuf_ShutdownFile_raft_5fserverpb_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<RaftSnapshotData> RaftSnapshotData_default_instance_;

// -------------------------------------------------------------------

class StoreIdent : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raft_serverpb.StoreIdent) */ {
 public:
  StoreIdent();
  virtual ~StoreIdent();

  StoreIdent(const StoreIdent& from);

  inline StoreIdent& operator=(const StoreIdent& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StoreIdent& default_instance();

  static const StoreIdent* internal_default_instance();

  void Swap(StoreIdent* other);

  // implements Message ----------------------------------------------

  inline StoreIdent* New() const { return New(NULL); }

  StoreIdent* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StoreIdent& from);
  void MergeFrom(const StoreIdent& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(StoreIdent* other);
  void UnsafeMergeFrom(const StoreIdent& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 cluster_id = 1;
  bool has_cluster_id() const;
  void clear_cluster_id();
  static const int kClusterIdFieldNumber = 1;
  ::google::protobuf::uint64 cluster_id() const;
  void set_cluster_id(::google::protobuf::uint64 value);

  // optional uint64 store_id = 2;
  bool has_store_id() const;
  void clear_store_id();
  static const int kStoreIdFieldNumber = 2;
  ::google::protobuf::uint64 store_id() const;
  void set_store_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:raft_serverpb.StoreIdent)
 private:
  inline void set_has_cluster_id();
  inline void clear_has_cluster_id();
  inline void set_has_store_id();
  inline void clear_has_store_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::uint64 cluster_id_;
  ::google::protobuf::uint64 store_id_;
  friend void  protobuf_InitDefaults_raft_5fserverpb_2eproto_impl();
  friend void  protobuf_AddDesc_raft_5fserverpb_2eproto_impl();
  friend void protobuf_AssignDesc_raft_5fserverpb_2eproto();
  friend void protobuf_ShutdownFile_raft_5fserverpb_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<StoreIdent> StoreIdent_default_instance_;

// -------------------------------------------------------------------

class RaftLocalState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raft_serverpb.RaftLocalState) */ {
 public:
  RaftLocalState();
  virtual ~RaftLocalState();

  RaftLocalState(const RaftLocalState& from);

  inline RaftLocalState& operator=(const RaftLocalState& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RaftLocalState& default_instance();

  static const RaftLocalState* internal_default_instance();

  void Swap(RaftLocalState* other);

  // implements Message ----------------------------------------------

  inline RaftLocalState* New() const { return New(NULL); }

  RaftLocalState* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RaftLocalState& from);
  void MergeFrom(const RaftLocalState& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RaftLocalState* other);
  void UnsafeMergeFrom(const RaftLocalState& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .eraftpb.HardState hard_state = 1;
  bool has_hard_state() const;
  void clear_hard_state();
  static const int kHardStateFieldNumber = 1;
  const ::eraftpb::HardState& hard_state() const;
  ::eraftpb::HardState* mutable_hard_state();
  ::eraftpb::HardState* release_hard_state();
  void set_allocated_hard_state(::eraftpb::HardState* hard_state);

  // optional uint64 last_index = 2;
  bool has_last_index() const;
  void clear_last_index();
  static const int kLastIndexFieldNumber = 2;
  ::google::protobuf::uint64 last_index() const;
  void set_last_index(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:raft_serverpb.RaftLocalState)
 private:
  inline void set_has_hard_state();
  inline void clear_has_hard_state();
  inline void set_has_last_index();
  inline void clear_has_last_index();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::eraftpb::HardState* hard_state_;
  ::google::protobuf::uint64 last_index_;
  friend void  protobuf_InitDefaults_raft_5fserverpb_2eproto_impl();
  friend void  protobuf_AddDesc_raft_5fserverpb_2eproto_impl();
  friend void protobuf_AssignDesc_raft_5fserverpb_2eproto();
  friend void protobuf_ShutdownFile_raft_5fserverpb_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<RaftLocalState> RaftLocalState_default_instance_;

// -------------------------------------------------------------------

class RaftApplyState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raft_serverpb.RaftApplyState) */ {
 public:
  RaftApplyState();
  virtual ~RaftApplyState();

  RaftApplyState(const RaftApplyState& from);

  inline RaftApplyState& operator=(const RaftApplyState& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RaftApplyState& default_instance();

  static const RaftApplyState* internal_default_instance();

  void Swap(RaftApplyState* other);

  // implements Message ----------------------------------------------

  inline RaftApplyState* New() const { return New(NULL); }

  RaftApplyState* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RaftApplyState& from);
  void MergeFrom(const RaftApplyState& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RaftApplyState* other);
  void UnsafeMergeFrom(const RaftApplyState& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 applied_index = 1;
  bool has_applied_index() const;
  void clear_applied_index();
  static const int kAppliedIndexFieldNumber = 1;
  ::google::protobuf::uint64 applied_index() const;
  void set_applied_index(::google::protobuf::uint64 value);

  // optional .raft_serverpb.RaftTruncatedState truncated_state = 2;
  bool has_truncated_state() const;
  void clear_truncated_state();
  static const int kTruncatedStateFieldNumber = 2;
  const ::raft_serverpb::RaftTruncatedState& truncated_state() const;
  ::raft_serverpb::RaftTruncatedState* mutable_truncated_state();
  ::raft_serverpb::RaftTruncatedState* release_truncated_state();
  void set_allocated_truncated_state(::raft_serverpb::RaftTruncatedState* truncated_state);

  // @@protoc_insertion_point(class_scope:raft_serverpb.RaftApplyState)
 private:
  inline void set_has_applied_index();
  inline void clear_has_applied_index();
  inline void set_has_truncated_state();
  inline void clear_has_truncated_state();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::raft_serverpb::RaftTruncatedState* truncated_state_;
  ::google::protobuf::uint64 applied_index_;
  friend void  protobuf_InitDefaults_raft_5fserverpb_2eproto_impl();
  friend void  protobuf_AddDesc_raft_5fserverpb_2eproto_impl();
  friend void protobuf_AssignDesc_raft_5fserverpb_2eproto();
  friend void protobuf_ShutdownFile_raft_5fserverpb_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<RaftApplyState> RaftApplyState_default_instance_;

// -------------------------------------------------------------------

class RegionLocalState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raft_serverpb.RegionLocalState) */ {
 public:
  RegionLocalState();
  virtual ~RegionLocalState();

  RegionLocalState(const RegionLocalState& from);

  inline RegionLocalState& operator=(const RegionLocalState& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RegionLocalState& default_instance();

  static const RegionLocalState* internal_default_instance();

  void Swap(RegionLocalState* other);

  // implements Message ----------------------------------------------

  inline RegionLocalState* New() const { return New(NULL); }

  RegionLocalState* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RegionLocalState& from);
  void MergeFrom(const RegionLocalState& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RegionLocalState* other);
  void UnsafeMergeFrom(const RegionLocalState& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .raft_serverpb.PeerState state = 1;
  bool has_state() const;
  void clear_state();
  static const int kStateFieldNumber = 1;
  ::raft_serverpb::PeerState state() const;
  void set_state(::raft_serverpb::PeerState value);

  // optional .metapb.Region region = 2;
  bool has_region() const;
  void clear_region();
  static const int kRegionFieldNumber = 2;
  const ::metapb::Region& region() const;
  ::metapb::Region* mutable_region();
  ::metapb::Region* release_region();
  void set_allocated_region(::metapb::Region* region);

  // @@protoc_insertion_point(class_scope:raft_serverpb.RegionLocalState)
 private:
  inline void set_has_state();
  inline void clear_has_state();
  inline void set_has_region();
  inline void clear_has_region();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::metapb::Region* region_;
  int state_;
  friend void  protobuf_InitDefaults_raft_5fserverpb_2eproto_impl();
  friend void  protobuf_AddDesc_raft_5fserverpb_2eproto_impl();
  friend void protobuf_AssignDesc_raft_5fserverpb_2eproto();
  friend void protobuf_ShutdownFile_raft_5fserverpb_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<RegionLocalState> RegionLocalState_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// RaftMessage

// optional uint64 region_id = 1;
inline bool RaftMessage::has_region_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RaftMessage::set_has_region_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RaftMessage::clear_has_region_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RaftMessage::clear_region_id() {
  region_id_ = GOOGLE_ULONGLONG(0);
  clear_has_region_id();
}
inline ::google::protobuf::uint64 RaftMessage::region_id() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.RaftMessage.region_id)
  return region_id_;
}
inline void RaftMessage::set_region_id(::google::protobuf::uint64 value) {
  set_has_region_id();
  region_id_ = value;
  // @@protoc_insertion_point(field_set:raft_serverpb.RaftMessage.region_id)
}

// optional .metapb.Peer from_peer = 2;
inline bool RaftMessage::has_from_peer() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RaftMessage::set_has_from_peer() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RaftMessage::clear_has_from_peer() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RaftMessage::clear_from_peer() {
  if (from_peer_ != NULL) from_peer_->::metapb::Peer::Clear();
  clear_has_from_peer();
}
inline const ::metapb::Peer& RaftMessage::from_peer() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.RaftMessage.from_peer)
  return from_peer_ != NULL ? *from_peer_
                         : *::metapb::Peer::internal_default_instance();
}
inline ::metapb::Peer* RaftMessage::mutable_from_peer() {
  set_has_from_peer();
  if (from_peer_ == NULL) {
    from_peer_ = new ::metapb::Peer;
  }
  // @@protoc_insertion_point(field_mutable:raft_serverpb.RaftMessage.from_peer)
  return from_peer_;
}
inline ::metapb::Peer* RaftMessage::release_from_peer() {
  // @@protoc_insertion_point(field_release:raft_serverpb.RaftMessage.from_peer)
  clear_has_from_peer();
  ::metapb::Peer* temp = from_peer_;
  from_peer_ = NULL;
  return temp;
}
inline void RaftMessage::set_allocated_from_peer(::metapb::Peer* from_peer) {
  delete from_peer_;
  from_peer_ = from_peer;
  if (from_peer) {
    set_has_from_peer();
  } else {
    clear_has_from_peer();
  }
  // @@protoc_insertion_point(field_set_allocated:raft_serverpb.RaftMessage.from_peer)
}

// optional .metapb.Peer to_peer = 3;
inline bool RaftMessage::has_to_peer() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RaftMessage::set_has_to_peer() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RaftMessage::clear_has_to_peer() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RaftMessage::clear_to_peer() {
  if (to_peer_ != NULL) to_peer_->::metapb::Peer::Clear();
  clear_has_to_peer();
}
inline const ::metapb::Peer& RaftMessage::to_peer() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.RaftMessage.to_peer)
  return to_peer_ != NULL ? *to_peer_
                         : *::metapb::Peer::internal_default_instance();
}
inline ::metapb::Peer* RaftMessage::mutable_to_peer() {
  set_has_to_peer();
  if (to_peer_ == NULL) {
    to_peer_ = new ::metapb::Peer;
  }
  // @@protoc_insertion_point(field_mutable:raft_serverpb.RaftMessage.to_peer)
  return to_peer_;
}
inline ::metapb::Peer* RaftMessage::release_to_peer() {
  // @@protoc_insertion_point(field_release:raft_serverpb.RaftMessage.to_peer)
  clear_has_to_peer();
  ::metapb::Peer* temp = to_peer_;
  to_peer_ = NULL;
  return temp;
}
inline void RaftMessage::set_allocated_to_peer(::metapb::Peer* to_peer) {
  delete to_peer_;
  to_peer_ = to_peer;
  if (to_peer) {
    set_has_to_peer();
  } else {
    clear_has_to_peer();
  }
  // @@protoc_insertion_point(field_set_allocated:raft_serverpb.RaftMessage.to_peer)
}

// optional .eraftpb.Message message = 4;
inline bool RaftMessage::has_message() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RaftMessage::set_has_message() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RaftMessage::clear_has_message() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RaftMessage::clear_message() {
  if (message_ != NULL) message_->::eraftpb::Message::Clear();
  clear_has_message();
}
inline const ::eraftpb::Message& RaftMessage::message() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.RaftMessage.message)
  return message_ != NULL ? *message_
                         : *::eraftpb::Message::internal_default_instance();
}
inline ::eraftpb::Message* RaftMessage::mutable_message() {
  set_has_message();
  if (message_ == NULL) {
    message_ = new ::eraftpb::Message;
  }
  // @@protoc_insertion_point(field_mutable:raft_serverpb.RaftMessage.message)
  return message_;
}
inline ::eraftpb::Message* RaftMessage::release_message() {
  // @@protoc_insertion_point(field_release:raft_serverpb.RaftMessage.message)
  clear_has_message();
  ::eraftpb::Message* temp = message_;
  message_ = NULL;
  return temp;
}
inline void RaftMessage::set_allocated_message(::eraftpb::Message* message) {
  delete message_;
  message_ = message;
  if (message) {
    set_has_message();
  } else {
    clear_has_message();
  }
  // @@protoc_insertion_point(field_set_allocated:raft_serverpb.RaftMessage.message)
}

// optional .metapb.RegionEpoch region_epoch = 5;
inline bool RaftMessage::has_region_epoch() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RaftMessage::set_has_region_epoch() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RaftMessage::clear_has_region_epoch() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RaftMessage::clear_region_epoch() {
  if (region_epoch_ != NULL) region_epoch_->::metapb::RegionEpoch::Clear();
  clear_has_region_epoch();
}
inline const ::metapb::RegionEpoch& RaftMessage::region_epoch() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.RaftMessage.region_epoch)
  return region_epoch_ != NULL ? *region_epoch_
                         : *::metapb::RegionEpoch::internal_default_instance();
}
inline ::metapb::RegionEpoch* RaftMessage::mutable_region_epoch() {
  set_has_region_epoch();
  if (region_epoch_ == NULL) {
    region_epoch_ = new ::metapb::RegionEpoch;
  }
  // @@protoc_insertion_point(field_mutable:raft_serverpb.RaftMessage.region_epoch)
  return region_epoch_;
}
inline ::metapb::RegionEpoch* RaftMessage::release_region_epoch() {
  // @@protoc_insertion_point(field_release:raft_serverpb.RaftMessage.region_epoch)
  clear_has_region_epoch();
  ::metapb::RegionEpoch* temp = region_epoch_;
  region_epoch_ = NULL;
  return temp;
}
inline void RaftMessage::set_allocated_region_epoch(::metapb::RegionEpoch* region_epoch) {
  delete region_epoch_;
  region_epoch_ = region_epoch;
  if (region_epoch) {
    set_has_region_epoch();
  } else {
    clear_has_region_epoch();
  }
  // @@protoc_insertion_point(field_set_allocated:raft_serverpb.RaftMessage.region_epoch)
}

// optional bool is_tombstone = 6;
inline bool RaftMessage::has_is_tombstone() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RaftMessage::set_has_is_tombstone() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RaftMessage::clear_has_is_tombstone() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RaftMessage::clear_is_tombstone() {
  is_tombstone_ = false;
  clear_has_is_tombstone();
}
inline bool RaftMessage::is_tombstone() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.RaftMessage.is_tombstone)
  return is_tombstone_;
}
inline void RaftMessage::set_is_tombstone(bool value) {
  set_has_is_tombstone();
  is_tombstone_ = value;
  // @@protoc_insertion_point(field_set:raft_serverpb.RaftMessage.is_tombstone)
}

// optional bytes start_key = 7;
inline bool RaftMessage::has_start_key() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void RaftMessage::set_has_start_key() {
  _has_bits_[0] |= 0x00000040u;
}
inline void RaftMessage::clear_has_start_key() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void RaftMessage::clear_start_key() {
  start_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_start_key();
}
inline const ::std::string& RaftMessage::start_key() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.RaftMessage.start_key)
  return start_key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RaftMessage::set_start_key(const ::std::string& value) {
  set_has_start_key();
  start_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:raft_serverpb.RaftMessage.start_key)
}
inline void RaftMessage::set_start_key(const char* value) {
  set_has_start_key();
  start_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:raft_serverpb.RaftMessage.start_key)
}
inline void RaftMessage::set_start_key(const void* value, size_t size) {
  set_has_start_key();
  start_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:raft_serverpb.RaftMessage.start_key)
}
inline ::std::string* RaftMessage::mutable_start_key() {
  set_has_start_key();
  // @@protoc_insertion_point(field_mutable:raft_serverpb.RaftMessage.start_key)
  return start_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RaftMessage::release_start_key() {
  // @@protoc_insertion_point(field_release:raft_serverpb.RaftMessage.start_key)
  clear_has_start_key();
  return start_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RaftMessage::set_allocated_start_key(::std::string* start_key) {
  if (start_key != NULL) {
    set_has_start_key();
  } else {
    clear_has_start_key();
  }
  start_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), start_key);
  // @@protoc_insertion_point(field_set_allocated:raft_serverpb.RaftMessage.start_key)
}

// optional bytes end_key = 8;
inline bool RaftMessage::has_end_key() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void RaftMessage::set_has_end_key() {
  _has_bits_[0] |= 0x00000080u;
}
inline void RaftMessage::clear_has_end_key() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void RaftMessage::clear_end_key() {
  end_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_end_key();
}
inline const ::std::string& RaftMessage::end_key() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.RaftMessage.end_key)
  return end_key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RaftMessage::set_end_key(const ::std::string& value) {
  set_has_end_key();
  end_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:raft_serverpb.RaftMessage.end_key)
}
inline void RaftMessage::set_end_key(const char* value) {
  set_has_end_key();
  end_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:raft_serverpb.RaftMessage.end_key)
}
inline void RaftMessage::set_end_key(const void* value, size_t size) {
  set_has_end_key();
  end_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:raft_serverpb.RaftMessage.end_key)
}
inline ::std::string* RaftMessage::mutable_end_key() {
  set_has_end_key();
  // @@protoc_insertion_point(field_mutable:raft_serverpb.RaftMessage.end_key)
  return end_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RaftMessage::release_end_key() {
  // @@protoc_insertion_point(field_release:raft_serverpb.RaftMessage.end_key)
  clear_has_end_key();
  return end_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RaftMessage::set_allocated_end_key(::std::string* end_key) {
  if (end_key != NULL) {
    set_has_end_key();
  } else {
    clear_has_end_key();
  }
  end_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), end_key);
  // @@protoc_insertion_point(field_set_allocated:raft_serverpb.RaftMessage.end_key)
}

inline const RaftMessage* RaftMessage::internal_default_instance() {
  return &RaftMessage_default_instance_.get();
}
// -------------------------------------------------------------------

// RaftTruncatedState

// optional uint64 index = 1;
inline bool RaftTruncatedState::has_index() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RaftTruncatedState::set_has_index() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RaftTruncatedState::clear_has_index() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RaftTruncatedState::clear_index() {
  index_ = GOOGLE_ULONGLONG(0);
  clear_has_index();
}
inline ::google::protobuf::uint64 RaftTruncatedState::index() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.RaftTruncatedState.index)
  return index_;
}
inline void RaftTruncatedState::set_index(::google::protobuf::uint64 value) {
  set_has_index();
  index_ = value;
  // @@protoc_insertion_point(field_set:raft_serverpb.RaftTruncatedState.index)
}

// optional uint64 term = 2;
inline bool RaftTruncatedState::has_term() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RaftTruncatedState::set_has_term() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RaftTruncatedState::clear_has_term() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RaftTruncatedState::clear_term() {
  term_ = GOOGLE_ULONGLONG(0);
  clear_has_term();
}
inline ::google::protobuf::uint64 RaftTruncatedState::term() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.RaftTruncatedState.term)
  return term_;
}
inline void RaftTruncatedState::set_term(::google::protobuf::uint64 value) {
  set_has_term();
  term_ = value;
  // @@protoc_insertion_point(field_set:raft_serverpb.RaftTruncatedState.term)
}

inline const RaftTruncatedState* RaftTruncatedState::internal_default_instance() {
  return &RaftTruncatedState_default_instance_.get();
}
// -------------------------------------------------------------------

// KeyValue

// optional bytes key = 1;
inline bool KeyValue::has_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void KeyValue::set_has_key() {
  _has_bits_[0] |= 0x00000001u;
}
inline void KeyValue::clear_has_key() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void KeyValue::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_key();
}
inline const ::std::string& KeyValue::key() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.KeyValue.key)
  return key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void KeyValue::set_key(const ::std::string& value) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:raft_serverpb.KeyValue.key)
}
inline void KeyValue::set_key(const char* value) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:raft_serverpb.KeyValue.key)
}
inline void KeyValue::set_key(const void* value, size_t size) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:raft_serverpb.KeyValue.key)
}
inline ::std::string* KeyValue::mutable_key() {
  set_has_key();
  // @@protoc_insertion_point(field_mutable:raft_serverpb.KeyValue.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* KeyValue::release_key() {
  // @@protoc_insertion_point(field_release:raft_serverpb.KeyValue.key)
  clear_has_key();
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void KeyValue::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    set_has_key();
  } else {
    clear_has_key();
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:raft_serverpb.KeyValue.key)
}

// optional bytes value = 2;
inline bool KeyValue::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void KeyValue::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void KeyValue::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void KeyValue::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value();
}
inline const ::std::string& KeyValue::value() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.KeyValue.value)
  return value_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void KeyValue::set_value(const ::std::string& value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:raft_serverpb.KeyValue.value)
}
inline void KeyValue::set_value(const char* value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:raft_serverpb.KeyValue.value)
}
inline void KeyValue::set_value(const void* value, size_t size) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:raft_serverpb.KeyValue.value)
}
inline ::std::string* KeyValue::mutable_value() {
  set_has_value();
  // @@protoc_insertion_point(field_mutable:raft_serverpb.KeyValue.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* KeyValue::release_value() {
  // @@protoc_insertion_point(field_release:raft_serverpb.KeyValue.value)
  clear_has_value();
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void KeyValue::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    set_has_value();
  } else {
    clear_has_value();
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:raft_serverpb.KeyValue.value)
}

inline const KeyValue* KeyValue::internal_default_instance() {
  return &KeyValue_default_instance_.get();
}
// -------------------------------------------------------------------

// RaftSnapshotData

// optional .metapb.Region region = 1;
inline bool RaftSnapshotData::has_region() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RaftSnapshotData::set_has_region() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RaftSnapshotData::clear_has_region() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RaftSnapshotData::clear_region() {
  if (region_ != NULL) region_->::metapb::Region::Clear();
  clear_has_region();
}
inline const ::metapb::Region& RaftSnapshotData::region() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.RaftSnapshotData.region)
  return region_ != NULL ? *region_
                         : *::metapb::Region::internal_default_instance();
}
inline ::metapb::Region* RaftSnapshotData::mutable_region() {
  set_has_region();
  if (region_ == NULL) {
    region_ = new ::metapb::Region;
  }
  // @@protoc_insertion_point(field_mutable:raft_serverpb.RaftSnapshotData.region)
  return region_;
}
inline ::metapb::Region* RaftSnapshotData::release_region() {
  // @@protoc_insertion_point(field_release:raft_serverpb.RaftSnapshotData.region)
  clear_has_region();
  ::metapb::Region* temp = region_;
  region_ = NULL;
  return temp;
}
inline void RaftSnapshotData::set_allocated_region(::metapb::Region* region) {
  delete region_;
  region_ = region;
  if (region) {
    set_has_region();
  } else {
    clear_has_region();
  }
  // @@protoc_insertion_point(field_set_allocated:raft_serverpb.RaftSnapshotData.region)
}

// optional uint64 file_size = 2;
inline bool RaftSnapshotData::has_file_size() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RaftSnapshotData::set_has_file_size() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RaftSnapshotData::clear_has_file_size() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RaftSnapshotData::clear_file_size() {
  file_size_ = GOOGLE_ULONGLONG(0);
  clear_has_file_size();
}
inline ::google::protobuf::uint64 RaftSnapshotData::file_size() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.RaftSnapshotData.file_size)
  return file_size_;
}
inline void RaftSnapshotData::set_file_size(::google::protobuf::uint64 value) {
  set_has_file_size();
  file_size_ = value;
  // @@protoc_insertion_point(field_set:raft_serverpb.RaftSnapshotData.file_size)
}

// repeated .raft_serverpb.KeyValue data = 3;
inline int RaftSnapshotData::data_size() const {
  return data_.size();
}
inline void RaftSnapshotData::clear_data() {
  data_.Clear();
}
inline const ::raft_serverpb::KeyValue& RaftSnapshotData::data(int index) const {
  // @@protoc_insertion_point(field_get:raft_serverpb.RaftSnapshotData.data)
  return data_.Get(index);
}
inline ::raft_serverpb::KeyValue* RaftSnapshotData::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:raft_serverpb.RaftSnapshotData.data)
  return data_.Mutable(index);
}
inline ::raft_serverpb::KeyValue* RaftSnapshotData::add_data() {
  // @@protoc_insertion_point(field_add:raft_serverpb.RaftSnapshotData.data)
  return data_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::raft_serverpb::KeyValue >*
RaftSnapshotData::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:raft_serverpb.RaftSnapshotData.data)
  return &data_;
}
inline const ::google::protobuf::RepeatedPtrField< ::raft_serverpb::KeyValue >&
RaftSnapshotData::data() const {
  // @@protoc_insertion_point(field_list:raft_serverpb.RaftSnapshotData.data)
  return data_;
}

inline const RaftSnapshotData* RaftSnapshotData::internal_default_instance() {
  return &RaftSnapshotData_default_instance_.get();
}
// -------------------------------------------------------------------

// StoreIdent

// optional uint64 cluster_id = 1;
inline bool StoreIdent::has_cluster_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StoreIdent::set_has_cluster_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StoreIdent::clear_has_cluster_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StoreIdent::clear_cluster_id() {
  cluster_id_ = GOOGLE_ULONGLONG(0);
  clear_has_cluster_id();
}
inline ::google::protobuf::uint64 StoreIdent::cluster_id() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.StoreIdent.cluster_id)
  return cluster_id_;
}
inline void StoreIdent::set_cluster_id(::google::protobuf::uint64 value) {
  set_has_cluster_id();
  cluster_id_ = value;
  // @@protoc_insertion_point(field_set:raft_serverpb.StoreIdent.cluster_id)
}

// optional uint64 store_id = 2;
inline bool StoreIdent::has_store_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void StoreIdent::set_has_store_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void StoreIdent::clear_has_store_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void StoreIdent::clear_store_id() {
  store_id_ = GOOGLE_ULONGLONG(0);
  clear_has_store_id();
}
inline ::google::protobuf::uint64 StoreIdent::store_id() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.StoreIdent.store_id)
  return store_id_;
}
inline void StoreIdent::set_store_id(::google::protobuf::uint64 value) {
  set_has_store_id();
  store_id_ = value;
  // @@protoc_insertion_point(field_set:raft_serverpb.StoreIdent.store_id)
}

inline const StoreIdent* StoreIdent::internal_default_instance() {
  return &StoreIdent_default_instance_.get();
}
// -------------------------------------------------------------------

// RaftLocalState

// optional .eraftpb.HardState hard_state = 1;
inline bool RaftLocalState::has_hard_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RaftLocalState::set_has_hard_state() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RaftLocalState::clear_has_hard_state() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RaftLocalState::clear_hard_state() {
  if (hard_state_ != NULL) hard_state_->::eraftpb::HardState::Clear();
  clear_has_hard_state();
}
inline const ::eraftpb::HardState& RaftLocalState::hard_state() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.RaftLocalState.hard_state)
  return hard_state_ != NULL ? *hard_state_
                         : *::eraftpb::HardState::internal_default_instance();
}
inline ::eraftpb::HardState* RaftLocalState::mutable_hard_state() {
  set_has_hard_state();
  if (hard_state_ == NULL) {
    hard_state_ = new ::eraftpb::HardState;
  }
  // @@protoc_insertion_point(field_mutable:raft_serverpb.RaftLocalState.hard_state)
  return hard_state_;
}
inline ::eraftpb::HardState* RaftLocalState::release_hard_state() {
  // @@protoc_insertion_point(field_release:raft_serverpb.RaftLocalState.hard_state)
  clear_has_hard_state();
  ::eraftpb::HardState* temp = hard_state_;
  hard_state_ = NULL;
  return temp;
}
inline void RaftLocalState::set_allocated_hard_state(::eraftpb::HardState* hard_state) {
  delete hard_state_;
  hard_state_ = hard_state;
  if (hard_state) {
    set_has_hard_state();
  } else {
    clear_has_hard_state();
  }
  // @@protoc_insertion_point(field_set_allocated:raft_serverpb.RaftLocalState.hard_state)
}

// optional uint64 last_index = 2;
inline bool RaftLocalState::has_last_index() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RaftLocalState::set_has_last_index() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RaftLocalState::clear_has_last_index() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RaftLocalState::clear_last_index() {
  last_index_ = GOOGLE_ULONGLONG(0);
  clear_has_last_index();
}
inline ::google::protobuf::uint64 RaftLocalState::last_index() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.RaftLocalState.last_index)
  return last_index_;
}
inline void RaftLocalState::set_last_index(::google::protobuf::uint64 value) {
  set_has_last_index();
  last_index_ = value;
  // @@protoc_insertion_point(field_set:raft_serverpb.RaftLocalState.last_index)
}

inline const RaftLocalState* RaftLocalState::internal_default_instance() {
  return &RaftLocalState_default_instance_.get();
}
// -------------------------------------------------------------------

// RaftApplyState

// optional uint64 applied_index = 1;
inline bool RaftApplyState::has_applied_index() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RaftApplyState::set_has_applied_index() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RaftApplyState::clear_has_applied_index() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RaftApplyState::clear_applied_index() {
  applied_index_ = GOOGLE_ULONGLONG(0);
  clear_has_applied_index();
}
inline ::google::protobuf::uint64 RaftApplyState::applied_index() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.RaftApplyState.applied_index)
  return applied_index_;
}
inline void RaftApplyState::set_applied_index(::google::protobuf::uint64 value) {
  set_has_applied_index();
  applied_index_ = value;
  // @@protoc_insertion_point(field_set:raft_serverpb.RaftApplyState.applied_index)
}

// optional .raft_serverpb.RaftTruncatedState truncated_state = 2;
inline bool RaftApplyState::has_truncated_state() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RaftApplyState::set_has_truncated_state() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RaftApplyState::clear_has_truncated_state() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RaftApplyState::clear_truncated_state() {
  if (truncated_state_ != NULL) truncated_state_->::raft_serverpb::RaftTruncatedState::Clear();
  clear_has_truncated_state();
}
inline const ::raft_serverpb::RaftTruncatedState& RaftApplyState::truncated_state() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.RaftApplyState.truncated_state)
  return truncated_state_ != NULL ? *truncated_state_
                         : *::raft_serverpb::RaftTruncatedState::internal_default_instance();
}
inline ::raft_serverpb::RaftTruncatedState* RaftApplyState::mutable_truncated_state() {
  set_has_truncated_state();
  if (truncated_state_ == NULL) {
    truncated_state_ = new ::raft_serverpb::RaftTruncatedState;
  }
  // @@protoc_insertion_point(field_mutable:raft_serverpb.RaftApplyState.truncated_state)
  return truncated_state_;
}
inline ::raft_serverpb::RaftTruncatedState* RaftApplyState::release_truncated_state() {
  // @@protoc_insertion_point(field_release:raft_serverpb.RaftApplyState.truncated_state)
  clear_has_truncated_state();
  ::raft_serverpb::RaftTruncatedState* temp = truncated_state_;
  truncated_state_ = NULL;
  return temp;
}
inline void RaftApplyState::set_allocated_truncated_state(::raft_serverpb::RaftTruncatedState* truncated_state) {
  delete truncated_state_;
  truncated_state_ = truncated_state;
  if (truncated_state) {
    set_has_truncated_state();
  } else {
    clear_has_truncated_state();
  }
  // @@protoc_insertion_point(field_set_allocated:raft_serverpb.RaftApplyState.truncated_state)
}

inline const RaftApplyState* RaftApplyState::internal_default_instance() {
  return &RaftApplyState_default_instance_.get();
}
// -------------------------------------------------------------------

// RegionLocalState

// optional .raft_serverpb.PeerState state = 1;
inline bool RegionLocalState::has_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RegionLocalState::set_has_state() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RegionLocalState::clear_has_state() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RegionLocalState::clear_state() {
  state_ = 0;
  clear_has_state();
}
inline ::raft_serverpb::PeerState RegionLocalState::state() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.RegionLocalState.state)
  return static_cast< ::raft_serverpb::PeerState >(state_);
}
inline void RegionLocalState::set_state(::raft_serverpb::PeerState value) {
  assert(::raft_serverpb::PeerState_IsValid(value));
  set_has_state();
  state_ = value;
  // @@protoc_insertion_point(field_set:raft_serverpb.RegionLocalState.state)
}

// optional .metapb.Region region = 2;
inline bool RegionLocalState::has_region() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RegionLocalState::set_has_region() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RegionLocalState::clear_has_region() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RegionLocalState::clear_region() {
  if (region_ != NULL) region_->::metapb::Region::Clear();
  clear_has_region();
}
inline const ::metapb::Region& RegionLocalState::region() const {
  // @@protoc_insertion_point(field_get:raft_serverpb.RegionLocalState.region)
  return region_ != NULL ? *region_
                         : *::metapb::Region::internal_default_instance();
}
inline ::metapb::Region* RegionLocalState::mutable_region() {
  set_has_region();
  if (region_ == NULL) {
    region_ = new ::metapb::Region;
  }
  // @@protoc_insertion_point(field_mutable:raft_serverpb.RegionLocalState.region)
  return region_;
}
inline ::metapb::Region* RegionLocalState::release_region() {
  // @@protoc_insertion_point(field_release:raft_serverpb.RegionLocalState.region)
  clear_has_region();
  ::metapb::Region* temp = region_;
  region_ = NULL;
  return temp;
}
inline void RegionLocalState::set_allocated_region(::metapb::Region* region) {
  delete region_;
  region_ = region;
  if (region) {
    set_has_region();
  } else {
    clear_has_region();
  }
  // @@protoc_insertion_point(field_set_allocated:raft_serverpb.RegionLocalState.region)
}

inline const RegionLocalState* RegionLocalState::internal_default_instance() {
  return &RegionLocalState_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace raft_serverpb

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::raft_serverpb::PeerState> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::raft_serverpb::PeerState>() {
  return ::raft_serverpb::PeerState_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_raft_5fserverpb_2eproto__INCLUDED
